### ISSUE TITLE
protocol error: promised `X` bytes in enveloped message, got `Y` bytes

### ISSUE THREAD

**Issue by DenisCarriere** [pinax-network/substreams-sink-webhook#11]
When using https://github.com/pinax-network/substreams-clock/releases/download/v0.1.0/clock-v0.1.0.spkg

```
file:///Users/denis/Github/substreams-sink-webhook/node_modules/@bufbuild/connect-node/node_modules/@bufbuild/connect/dist/esm/protocol/async-iterable.js:604
                throw new ConnectError(message, Code.InvalidArgument);
                      ^

ConnectError: [invalid_argument] protocol error: promised 486 bytes in enveloped message, got 470 bytes
    at file:///Users/denis/Github/substreams-sink-webhook/node_modules/@bufbuild/connect-node/node_modules/@bufbuild/connect/dist/esm/protocol/async-iterable.js:604:23
    at Generator.next (<anonymous>)
    at resume (file:///Users/denis/Github/substreams-sink-webhook/node_modules/@bufbuild/connect-node/node_modules/@bufbuild/connect/dist/esm/protocol/async-iterable.js:27:44)
    at fulfill (file:///Users/denis/Github/substreams-sink-webhook/node_modules/@bufbuild/connect-node/node_modules/@bufbuild/connect/dist/esm/protocol/async-iterable.js:29:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  rawMessage: 'protocol error: promised 486 bytes in enveloped message, got 470 bytes',
  code: 3,
  metadata: Headers {
    [Symbol(headers list)]: HeadersList {
      cookies: null,
      [Symbol(headers map)]: Map(0) {},
      [Symbol(headers map sorted)]: null
    },
    [Symbol(guard)]: 'none'
  },
  details: [],
  cause: undefined
}
```

**Comment by DenisCarriere** [comment]
Seems related to ConnectWeb & Substreams
